"""src/protocols.py — Protocol definitions for dependency injection."""
from __future__ import annotations

from typing import Dict, List, Optional, Protocol, Tuple

from src.types import Platform, StrategyId


class PortfolioProvider(Protocol):
    def cash_usdc(self) -> float: ...
    def peak_equity(self) -> float: ...
    def get_portfolio_mtm(self) -> "PortfolioSnapshot": ...
    def get_delta(self, market_id: str, platform: Platform) -> "Delta": ...
    def get_market_exposure_usdc(self, market_id: str) -> float: ...
    def get_price_age_ms(self) -> int: ...


class MarketDataProvider(Protocol):
    def get_snapshot(self, market_id: str, platform: Platform) -> Optional["MarketSnapshot"]: ...
    def get_mid_prices(self, market_id: str, platform: Platform) -> Optional[Tuple[float, float]]: ...
    def get_all_markets(self) -> set[str]: ...
    def get_health(self) -> dict: ...


class PortfolioStore(Protocol):
    def save_fill_and_position(self, fill, position, cash, peak, pnl) -> None: ...
    def load_state(self) -> dict: ...
    def save_order(self, proposal_id, submission_json, exchange_order_id) -> None: ...
    def load_active_orders(self) -> List[Tuple[str, Optional[str], str]]: ...
    def remove_order(self, proposal_id) -> None: ...
    def save_reservation(self, proposal_id, amount, platform, strategy_id) -> None: ...
    def remove_reservation(self, proposal_id) -> None: ...
    def load_reservations(self) -> Dict[str, Tuple[float, Platform, StrategyId]]: ...
    def save_kill_switch(self, active: bool) -> None: ...
    def load_kill_switch(self) -> bool: ...
    def close(self) -> None: ...
    def is_healthy(self) -> bool: ...
