"""src/protocols.py — Protocol definitions for dependency injection."""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, Tuple

from src.enums import Platform, StrategyId

# Forward references for circular import avoidance
if False:
    from portfolio.manager import DeltaResult, PortfolioMTM
    from data.models import MarketSnapshot


class PortfolioProvider(Protocol):
    def cash_usdc(self) -> float: ...
    def peak_equity(self) -> float: ...
    def get_portfolio_mtm(self) -> "PortfolioMTM": ...
    def get_delta(self, market_id: str, platform: Platform) -> "DeltaResult": ...
    def get_market_exposure_usdc(self, market_id: str) -> float: ...
    def get_price_age_ms(self) -> int: ...


class MarketDataProvider(Protocol):
    def get_snapshot(self, market_id: str, platform: Platform) -> Optional["MarketSnapshot"]: ...
    def get_mid_prices(self, market_id: str, platform: Platform) -> Optional[Tuple[float, float]]: ...
    def get_all_markets(self) -> set[str]: ...
    def get_health(self) -> Dict[str, Any]: ...


class PortfolioStore(Protocol):
    def save_fill_and_position(self, fill: Any, position: Any, cash: float, peak: float, pnl: float) -> None: ...
    def load_state(self) -> Dict[str, Any]: ...
    def save_order(self, proposal_id: str, submission_json: str, exchange_order_id: Optional[str]) -> None: ...
    def load_active_orders(self) -> List[Tuple[str, Optional[str], str]]: ...
    def remove_order(self, proposal_id: str) -> None: ...
    def save_reservation(self, proposal_id: str, amount: float, platform: Platform, strategy_id: StrategyId) -> None: ...
    def remove_reservation(self, proposal_id: str) -> None: ...
    def load_reservations(self) -> Dict[str, Tuple[float, Platform, StrategyId]]: ...
    def save_kill_switch(self, active: bool) -> None: ...
    def load_kill_switch(self) -> bool: ...
    def close(self) -> None: ...
    def is_healthy(self) -> bool: ...
    def update_order_exchange_id(self, proposal_id: str, exchange_order_id: str) -> None: ...


class RiskStore(Protocol):
    """Persistence surface the RiskEngine depends on (DR for reservations / kill switch)."""

    def save_reservation(self, proposal_id: str, amount: float, platform: Platform, strategy_id: StrategyId) -> None: ...
    def remove_reservation(self, proposal_id: str) -> None: ...
    def load_reservations(self) -> Dict[str, Tuple[float, Platform, StrategyId]]: ...
    def save_kill_switch(self, active: bool) -> None: ...
    def load_kill_switch(self) -> bool: ...
